# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# INSTALL PLUGIN RELLOAD
unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "gusztavvargadr/ubuntu-desktop"
  config.vm.box_download_insecure=true
  config.vbguest.no_install  = true
  config.vbguest.auto_update = false
  config.vbguest.no_remote   = true

  # VM ubuntu-desktop
  config.vm.define "ubuntuDesktop-lpic-201"  do |ubuntuDesktop_lpic_102|

    # VARIABLE HOSTNAME
    APP_NAME= "ubuntu-desktop-lpic-201"

    # HOSTNAME
    ubuntuDesktop_lpic_102.vm.hostname = APP_NAME

    # NETWORK
    ubuntuDesktop_lpic_102.vm.network "public_network" ,ip: "192.168.0.138",mode: "bridge" ,bridge: [
    "ens32",
    "Marvell AQtion 5Gbit Network Adapter"
    ]

    # MOUNTS
    ubuntuDesktop_lpic_102.vm.synced_folder ".", "/vagrant", disabled: true
    ubuntuDesktop_lpic_102.vm.synced_folder "../security", "/home/vagrant//security"
    ubuntuDesktop_lpic_102.vm.synced_folder "../configs", "/home/vagrant/configs"

    # PROVIDER
    ubuntuDesktop_lpic_102.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name = APP_NAME
      vb.memory = 2048
      vb.cpus = 1
    end

    # PROVISION
    ubuntuDesktop_lpic_102.vm.provision "shell", path: "../scripts/install.sh"
  end

end
