# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# INSTALL PLUGIN RELLOAD
unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "generic/fedora28"
  config.vm.box_download_insecure=true

  # VM srv01
  config.vm.define "fedora-lpic-201"  do |fedora_lic_102|

    # VARIABLE HOSTNAME
    APP_NAME= "fedora-lpic-201"

    # HOSTNAME
    fedora_lic_102.vm.hostname = APP_NAME

    # NETWORK
    fedora_lic_102.vm.network "public_network" ,ip: "192.168.0.139",mode: "bridge",bridge: [
    "ens32",
    "Marvell AQtion 5Gbit Network Adapter"
    ]

    # MOUNTS
    fedora_lic_102.vm.synced_folder ".", "/vagrant", disabled: true
    fedora_lic_102.vm.synced_folder "./security", "/home/vagrant/security"
    fedora_lic_102.vm.synced_folder "./configs", "/home/vagrant/configs"

    # PROVIDER
    fedora_lic_102.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name = APP_NAME
      vb.memory = 2048
      vb.cpus = 1
    end

   # SHELL PROVISIONING
    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
    fedora_lic_102.vm.provision "shell", path: "scripts/install.sh"

  end

end